language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
#before_install:
#- chmod +x mvnw

addons:
  sonarcloud:
    organization: "sistexpedidos"
    token:
      secure: "$SONAR_KEY_CLOUD"
script:
  - sonar-scanner
deploy:
 provider: heroku
 api-key:
  secure: $SONAR_KEY_HEROKU
 app: interfacesistexpedidos
